
scannerConfigurations:

  301:
    process_key   : "Process_Pallet_putaway"
    pallet_expiry_threshold: "10"
    dim_fail      : "DIM_FAIL"
    weigh_fail    : "WEIGH_FAIL"
    other_fail    : "ASRS_UNKN"
    container_fail: "ASRS_UNKN"
    pallet_unknown: "ASRS_UNKN"
    pallet_expired: "EXP_PALLET"
    asrs_full     : "ASRS_FULL"
    recall_reject : "RECALL_REJECT"
    robo_depal    : "AUTO_DEPAL"
    manual_depal  : "MANL_DEPAL"
  
  201:
    process_key   : "Process_Pallet_routing_Scanner_201"
    container_fail: "DEPAL_REJECT"
    robo_depal    : "ROBO_DEPAL"
    manual_depal  : "MANL_DEPAL"
    recall_reject : "RECALL_REJECT"
    
  880:
    process_key   : "Process_Case_putaway"
    dim_fail      : "CASE_DIMFAIL"
    weigh_fail    : "CASE_DIMFAIL"
    other_fail    : "CASE_REJECT"
    container_fail: "CASE_REJECT"
    panda         : "TO_PANDA"
    case_unknown  : "CASE_UNKN"
    asrs_full     : "CASE_FULL"
  890:
    process_key   : "Process_aisle_scanner_putaway"
    dim_fail      : "CASE_DIMFAIL"
    weigh_fail    : "CASE_DIMFAIL"
    other_fail    : "CASE_REJECT"
    container_fail: "CASE_REJECT"
    case_unknown  : "CASE_UNKN"
    asrs_full     : "CASE_FULL"
    aisle 		  :
                    - name          : "SH08"
                      level         :
                                      - "011"
                                      - "012"
                                      - "013"
                                      - "014"
                                      - "015"
                                      - "016"
                                      - "017"
                                      - "018"
                                      - "019"
                                      - "020"
                    - name          : "SH07"
                      level         :
                                      - "011"
                                      - "012"
                                      - "013"
                                      - "014"
                                      - "015"
                                      - "016"
                                      - "017"
                                      - "018"
                                      - "019"
                                      - "020"
  889:
    process_key   : "Process_aisle_scanner_putaway"
    dim_fail      : "CASE_DIMFAIL"
    weigh_fail    : "CASE_DIMFAIL"
    other_fail    : "CASE_REJECT"
    container_fail: "CASE_REJECT"
    case_unknown  : "CASE_UNKN"
    asrs_full     : "CASE_FULL"
    aisle 		  :
                    - name          : "SH08"
                      level         :
                                      - "001"
                                      - "002"
                                      - "003"
                                      - "004"
                                      - "005"
                                      - "006"
                                      - "007"
                                      - "008"
                                      - "009"
                                      - "010"
                    - name          : "SH07"
                      level         :
                                      - "001"
                                      - "002"
                                      - "003"
                                      - "004"
                                      - "005"
                                      - "006"
                                      - "007"
                                      - "008"
                                      - "009"
                                      - "010"
  886:
    process_key   : "Process_aisle_scanner_putaway"
    dim_fail      : "CASE_DIMFAIL"
    weigh_fail    : "CASE_DIMFAIL"
    other_fail    : "CASE_REJECT"
    container_fail: "CASE_REJECT"
    case_unknown  : "CASE_UNKN"
    asrs_full     : "CASE_FULL"
    aisle 		  :
                    - name          : "SH_AISLE_L5"
                      level         :
                                      - "1"
                                      - "2"
                                      - "3"
                                      - "4"
                                      - "5"
                                      - "6"
                                      - "7"
                                      - "8"
                                      - "9"
                                      - "10"
                    - name          : "SH_AISLE_L6"
                      level         :
                                      - "1"
                                      - "2"
                                      - "3"
                                      - "4"
                                      - "5"
                                      - "6"
                                      - "7"
                                      - "8"
                                      - "9"
                                      - "10"
  887:
    process_key   : "Process_aisle_scanner_putaway"
    dim_fail      : "CASE_DIMFAIL"
    weigh_fail    : "CASE_DIMFAIL"
    other_fail    : "CASE_REJECT"
    container_fail: "CASE_REJECT"
    case_unknown  : "CASE_UNKN"
    asrs_full     : "CASE_FULL"
    aisle 		  :
                    - name          : "SH_AISLE_U5"
                      level         :
                                      - "11"
                                      - "12"
                                      - "13"
                                      - "14"
                                      - "15"
                                      - "16"
                                      - "17"
                                      - "18"
                                      - "19"
                                      - "20"
                    - name          : "SH_AISLE_U6"
                      level         :
                                      - "11"
                                      - "12"
                                      - "13"
                                      - "14"
                                      - "15"
                                      - "16"
                                      - "17"
                                      - "18"
                                      - "19"
                                      - "20"
  885:
    process_key   : "Process_aisle_scanner_putaway"
    dim_fail      : "CASE_DIMFAIL"
    weigh_fail    : "CASE_DIMFAIL"
    other_fail    : "CASE_REJECT"
    container_fail: "CASE_REJECT"
    case_unknown  : "CASE_UNKN"
    asrs_full     : "CASE_FULL"
    aisle 		  :
                    - name          : "SH_AISLE_U3"
                      level         :
                                      - "11"
                                      - "12"
                                      - "13"
                                      - "14"
                                      - "15"
                                      - "16"
                                      - "17"
                                      - "18"
                                      - "19"
                                      - "20"
                    - name          : "SH_AISLE_U4"
                      level         :
                                      - "11"
                                      - "12"
                                      - "13"
                                      - "14"
                                      - "15"
                                      - "16"
                                      - "17"
                                      - "18"
                                      - "19"
                                      - "20"
  884:
    process_key   : "Process_aisle_scanner_putaway"
    dim_fail      : "CASE_DIMFAIL"
    weigh_fail    : "CASE_DIMFAIL"
    other_fail    : "CASE_REJECT"
    container_fail: "CASE_REJECT"
    case_unknown  : "CASE_UNKN"
    asrs_full     : "CASE_FULL"
    aisle 		  :
                    - name          : "SH_AISLE_L3"
                      level         :
                                      - "1"
                                      - "2"
                                      - "3"
                                      - "4"
                                      - "5"
                                      - "6"
                                      - "7"
                                      - "8"
                                      - "9"
                                      - "10"
                    - name          : "SH_AISLE_L4"
                      level         :
                                      - "1"
                                      - "2"
                                      - "3"
                                      - "4"
                                      - "5"
                                      - "6"
                                      - "7"
                                      - "8"
                                      - "9"
                                      - "10"
  882:
    process_key   : "Process_aisle_scanner_putaway"
    dim_fail      : "CASE_DIMFAIL"
    weigh_fail    : "CASE_DIMFAIL"
    other_fail    : "CASE_REJECT"
    container_fail: "CASE_REJECT"
    case_unknown  : "CASE_UNKN"
    asrs_full     : "CASE_FULL"
    aisle 		  :
                    - name          : "SH_AISLE_U1"
                      level         :
                                      - "11"
                                      - "12"
                                      - "13"
                                      - "14"
                                      - "15"
                                      - "16"
                                      - "17"
                                      - "18"
                                      - "19"
                                      - "20"
                    - name          : "SH_AISLE_U2"
                      level         :
                                      - "11"
                                      - "12"
                                      - "13"
                                      - "14"
                                      - "15"
                                      - "16"
                                      - "17"
                                      - "18"
                                      - "19"
                                      - "20"
    
  881:
    process_key   : "Process_aisle_scanner_putaway"
    dim_fail      : "CASE_DIMFAIL"
    weigh_fail    : "CASE_DIMFAIL"
    other_fail    : "CASE_REJECT"
    container_fail: "CASE_REJECT"
    case_unknown  : "CASE_UNKN"
    asrs_full     : "CASE_FULL"
    aisle 		  :
                    - name          : "SH_AISLE_L1"
                      level         :
                                      - "1"
                                      - "2"
                                      - "3"
                                      - "4"
                                      - "5"
                                      - "6"
                                      - "7"
                                      - "8"
                                      - "9"
                                      - "10"
                    - name          : "SH_AISLE_L2"
                      level         :
                                      - "1"
                                      - "2"
                                      - "3"
                                      - "4"
                                      - "5"
                                      - "6"
                                      - "7"
                                      - "8"
                                      - "9"
                                      - "10"
